

services:
  neo4j:
    image: neo4j:2025.07.1-community
    container_name: knowledge-graph-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
      - ./neo4j/conf:/conf
    environment:
      - NEO4J_AUTH=neo4j/knowledge123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_db_tx__log_rotation_retention__policy=1 days
      # Enhanced memory settings for Neo4j 2025.07.1
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_memory_pagecache_size=512m
      # Enable server logs
      - NEO4J_dbms_logs_http_enabled=true
      - NEO4J_dbms_logs_query_enabled=INFO
      - NEO4J_dbms_logs_query_threshold=1s
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "knowledge123", "RETURN 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile.api
    container_name: knowledge-graph-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=knowledge123
      - NEO4J_DATABASE=neo4j
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DEBUG=false
      - LOG_LEVEL=INFO
    depends_on:
      neo4j:
        condition: service_healthy
    volumes:
      - ../src:/app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ui:
    build:
      context: ../
      dockerfile: docker/Dockerfile.ui
    container_name: knowledge-graph-ui
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - API_BASE_URL=http://api:8000
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ../src:/app/src

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  default:
    name: knowledge-graph-network
